### ISSUE TITLE
SpotMetrics not compiling 

### ISSUE THREAD

**Issue by giulia84x** [george-haddad/spotmetrics#6]
Hi, 

I'm having some issues running the plugin on Fiji on Windows 10. Same errors occur also by running it on a Mac.  

(1) the plugin runs but does not compile the file with the size/RGB of the spots; it does not provide an error message either; so I'm a bit lost at how to solve this issue. The plugin seems to count way more spots than the actual number visbile in the video (order of few thousands vs 10), regardless of how I change the estimated initial spot size. No tracks numebr appear under the root  menu at the end of the analysis. 

This it a typical log window message: 
"Detection processes 4 frames simultaneously and allocates 1 thread per frame.
 Found 2797 spots.
 Starting initial filtering process.
 Starting tracking process.
 Frame to frame LAP solved in 0.6 s.
 Cost matrix for track segments created in 0.3 s.
 Track segment LAP solved in 0.0 s."
 
(2) the plugin starts running and then it gets stuck, again without giving error messages. 
 
Do you have perphaps a test video that I could run with a pre-defined set of initial parameters to check that the plugin is working properly? 

Any insight would be very useful. 

Stay safe
Thank you,
Giulia

**Comment by george-haddad** [comment]
Hello, is there a place you can host the video (dropbox or google drive) so that I can download it and what the parameters were that you used for the plugin. This way  can try to reproduce what's happening on my end and try to debug the issue.

**Comment by giulia84x** [comment]
Hello George, 

please find here the video: [https://www.dropbox.com/s/vba4opalsx7wa1n/testsmall_cropped.avi?dl=0](url)
To run the analysis i started using the default parameters with the option "detect flash" left unchecked. I then tried to decrease the "subtract background" option from 50 to 30, set the "blob diametre" to 30 and increase the size of the particles in the analyzer, without much success. 

The plugin runs and there's enough memory available in the PC; it generates an excel spreadhseet but it is devoid of data and no track appears under the "root" in the analysis tab. I tried to load different videos and got the same results. 

Thank you, Giulia

**Comment by george-haddad** [comment]
Thank you for providing the video and the parameters you entered. I will try to run this on my end and see what's happening.

**Comment by giulia84x** [comment]
Hi George, 

I managed to get the plugin run on one image stack where the initial blob diameter to be measured was of the order of 10-30 pixels. Unfortunately, the problem still persists on image stacks where the initial blob diameter is much higher (~70 pixels) and during expansion it actually exceeds the "blob diameter max value" that can be set in "tracking menu" (reaching ~ 140-150 pixels). Could this be the issue? If so, could you please advise me on how to change the maximum blob diameter in the "tracking menu"?  

Thank you, Giulia

**Comment by george-haddad** [comment]
Hi Giulia,

I ran your video on SpotMetrics and also another video I had 3 years ago. It seems like no errors are actually thrown and more or less this should work, but it's not.

I suspect that as Fiji and it's combination of plugins (TrackMate, Particle Analyzer ...etc) get updated that it may have had side effects on SpotMetrics. When I conduct the analysis manually, the methods work fine, but when the same analysis is automated by SpotMetrics there seems to be some plugin that is not responding. I am suspecting it to be the TrackMate plugin.

I need to dig deeper into the code.

**Comment by george-haddad** [comment]
OK, I found the problem, nothing to do with the plugins but with a method we had called `filterTrackList()` 

https://github.com/george-haddad/spotmetrics/blob/3b5f1db993fcca32ddf56d8bd0ee2fe8509dd6f3/src/spotmetrics/analyzer/AnalysisEngine.java#L297-L321

It was apparently deleting all the collected tracks. Which is a bit weird because 3 years ago this was working just fine. Anyways, I remove the call to that method and it is populating the tracks fine.

I tried your video and your video needs some pre-processing.

- The frames in the video that has the flash looks all pinksh
- Set SpotMetrics flash detection to "Relaxed" that will work
- You can ultimately just delete the first 110 frame and have the video start right after the flash occurs
    - At this point you can disable flash detection feature altogether
- I set the track diameter to 40 pixel because there are big spots
- The video quality deteriorates throughout the end
    - Maybe to pick a different algorithm filter for turning the frames into black/white binary image

Here try using this version of SpotMetrics. Remove the SpotMetrics jar form Fiji and put this in its place.

https://github.com/george-haddad/spotmetrics/releases/tag/v2.10-beta

Try your tests with this one.

**Comment by giulia84x** [comment]
Hi George, 
apologies for the late reply. I finally managed to try the new version of SpotMetrics and it works! Thank you so much for updating it! 

The only issue which I still have is that the tracking of the particles get worse with time; by looking at the portion of the videos when this seems to happen more often, it seems that when the contrast difference between the substrate and the spot decreases the plugin cannot distinguish them properly anymore.  I tried changing the initial filter to turn the videos into black and white but without a clear improvement. Do you have any other suggestion on how to overcome this issue? 

Thank you, Giulia

**Comment by george-haddad** [comment]
Hi Giulia, Yes what you are experiencing is something we (the principal researcher and I) have encountered. The video that needs to be analyzed has to be for a certain quality and must have applied to it specifically tuned filters to be able to get the frames in a nice black and white format. This part of video frame editing and filtering is out of my scope, I'm mainly focused on the software quality and automation.

The section [Limitations and Considerations](https://www.frontiersin.org/articles/10.3389/fphys.2017.00106/full#h4) gives some insight about how video quality affects the outcome in the plugin. These were discovered by the principal researcher.

I hope this helps.

**Comment by giulia84x** [comment]
Hi George,

i had to take a break from this project, but now i’m back at it. i think all what you mentioned about video qualities makes perfect sense and I will try to acquire better and sort of cleaner video from now on.

I was wondering if there’s any way to change the upper limit for some of the parameters of Spotmetrics, such as “blob diameter” and “blob threshold” and especially of the parameters under the “tracking tab” (such as “gap closing max frame gap").

I found that by increasing most of the values of the parameters of the “tracking tab”, the plugin more easily recognise the blobs in my videos; on the other side it seems that it is assigning a different number to the same spot multiple times (see attached screenshot of the overlay) and i thought that by increasing the “gap closing max frame gap” should help, but i cannot increase it more than 20 frames. I also set “gap closing max distance” to the maximum (100 pixel) but that is relatively small for the high magnification videos.

I also wanted to ask you if you think that directly uploading to Spotmetrics an 8-bit stack, already thresholded and with the background subtracted would help the plugin. I tried a couple of times but it did not seem to make much difference.

Is there also a way to manually select the actual threshold value for a specific threshold method in Spotmetrics (under the processing tab)? I assume the “subtract background” value option refers to the rolling ball algorithm and not to the thresholding method; is this correct?

thanks for your insight!
I’m looking forward to hearing back from you!

Best,
Giulia


[cid:B3CF1984-3FAD-4E0B-A2DE-80360945D83A@hsd1.ma.comcast.net]


Best,
Giulia

Postdoctoral Scholar
Silklab, Suite 4875 , 200 Boston Ave
02155 Medford, MA USA
Department of Biomedical Engineering
Tufts University

On 1 May 2020, at 09:48, George Haddad <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Giulia, Yes what you are experiencing is something we (the principal researcher and I) have encountered. The video that needs to be analyzed has to be for a certain quality and must have applied to it specifically tuned filters to be able to get the frames in a nice black and white format. This part of video frame editing and filtering is out of my scope, I'm mainly focused on the software quality and automation.

The section Limitations and Considerations<https://www.frontiersin.org/articles/10.3389/fphys.2017.00106/full#h4> gives some insight about how video quality affects the outcome in the plugin. These were discovered by the principal researcher.

I hope this helps.

**Comment by giulia84x** [comment]
Hi George,

i’m not sure if you have already received the email i copy-pasted below (i think i might have sent it to the wrong address).

Thank you in advance for any insight you might have.


----------------------------------

Hi George,

i had to take a break from this project, but now i’m back at it. i think all what you mentioned about video qualities makes perfect sense and I will try to acquire better and sort of cleaner video from now on.

I was wondering if there’s any way to change the upper limit for some of the parameters of Spotmetrics, such as “blob diameter” and “blob threshold” and especially of the parameters under the “tracking tab” (such as “gap closing max frame gap").

I found that by increasing most of the values of the parameters of the “tracking tab”, the plugin more easily recognise the blobs in my videos; on the other side it seems that it is assigning a different number to the same spot multiple times (see attached screenshot of the overlay) and i thought that by increasing the “gap closing max frame gap” should help, but i cannot increase it more than 20 frames. I also set “gap closing max distance” to the maximum (100 pixel) but that is relatively small for the high magnification videos.

I also wanted to ask you if you think that directly uploading to Spotmetrics an 8-bit stack, already thresholded and with the background subtracted would help the plugin. I tried a couple of times but it did not seem to make much difference.

Is there also a way to manually select the actual threshold value for a specific threshold method in Spotmetrics (under the processing tab)? I assume the “subtract background” value option refers to the rolling ball algorithm and not to the thresholding method; is this correct?

thanks for your insight!
I’m looking forward to hearing back from you!

Best,
Giulia


[cid:B3CF1984-3FAD-4E0B-A2DE-80360945D83A@hsd1.ma.comcast.net]

----------------------------------


On 1 May 2020, at 09:48, George Haddad <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Giulia, Yes what you are experiencing is something we (the principal researcher and I) have encountered. The video that needs to be analyzed has to be for a certain quality and must have applied to it specifically tuned filters to be able to get the frames in a nice black and white format. This part of video frame editing and filtering is out of my scope, I'm mainly focused on the software quality and automation.

The section Limitations and Considerations<https://www.frontiersin.org/articles/10.3389/fphys.2017.00106/full#h4> gives some insight about how video quality affects the outcome in the plugin. These were discovered by the principal researcher.

I hope this helps.

**Comment by george-haddad** [comment]
Hi, I am aware of your github issue, I am just trying to find free time to respond and develop. All my work on Spotmetrics has been for free and during free time while having a full time job and family. I try to see what I can do and when I can do it so no promises. Though this is a fully open-source project and I would welcome contributors if there are any.

**Comment by giulia84x** [comment]
Dear George,

I’m sorry, I was unaware of the situation; please accept my apologies.
Of course, any help or suggestion when you have the time would be great.

I would be very happy to contribute; I just do not know how. I have never made a  dedicated plugin  like this one, but I would be happy to learn. Please let me know if there’s any other way in which I can contribute.

Best,
Giulia

Postdoctoral Scholar
Silklab, Suite 4875 , 200 Boston Ave
02155 Medford, MA USA
Department of Biomedical Engineering
Tufts University

**Comment by george-haddad** [comment]
Hi Giulia, I have not received your email but it's fine to discuss spotmetrics here as as github issue as it pertains to the software. You may want to holdback from pasting email addresses and personal information here as it is public without any privacy.

To address some of your questions concerning the processing of the video files. You are pretty much correct on what you are assuming sport metrics is doing. Below is a snippet of the Java method that performs the processing. I feel that is is at least readable to a certain degree that a non-programmer can understand it.

https://github.com/george-haddad/spotmetrics/blob/3b5f1db993fcca32ddf56d8bd0ee2fe8509dd6f3/src/spotmetrics/analyzer/AnalysisEngine.java#L151-L172

On increasing the blob diameter and other settings; that can be adjusted in SpotMetrics as they are just user defined parameters. So that probably will not be a problem to edit in the plugin. However the video processing might not be. So the whole purpose of SpotMetrics (or at least on of them) is to automate the tedious steps of  processing the videos.

What can be done, however is to parameterize more options to cover more use cases. When this plugin was created it was catered mostly to dealing with the videos from Stavros Hadjisolomou who used it in his research. One major part of getting good results was having access to videos for testing. If I am just blindly adjusting the software then I cannot ensure the quality of its output. It is usually better to have a 2 part collaboration.

1. Collaboration between you and Mr. Hadjisolomou on the quality of the videos
2. Collaboration between you and I on testing the videos and what options are needed

It may be true that SpotMetrics wasn't designed for videos with very large spots, it also was not designed to take in pre-processed videos. This might be a valid use case but I would need test videos to use in developing a new feature. Also any feature developed should be applicable to anyone who wants to use the plugin.

**Comment by giulia84x** [comment]
Hi George,

please let me know which of the above addresses you prefer me not to use and I will certainly do so.

I understand and agree with you on the need to share the videos in order to optimise the plugin. I have discussed this with my direct supervisor and now we are waiting for a response from the manager of this project. As soon as I have news I will let you know.

thank you

Best,
Giulia

Postdoctoral Scholar
Silklab, Suite 4875 , 200 Boston Ave
02155 Medford, MA USA
Department of Biomedical Engineering
Tufts University

On 12 Jun 2020, at 02:08, George Haddad <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Giulia, I have not received your email but it's fine to discuss spotmetrics here as as github issue as it pertains to the software. You may want to holdback from pasting email addresses and personal information here as it is public without any privacy.

To address some of your questions concerning the processing of the video files. You are pretty much correct on what you are assuming sport metrics is doing. Below is a snippet of the Java method that performs the processing. I feel that is is at least readable to a certain degree that a non-programmer can understand it.

https://github.com/george-haddad/spotmetrics/blob/3b5f1db993fcca32ddf56d8bd0ee2fe8509dd6f3/src/spotmetrics/analyzer/AnalysisEngine.java#L151-L172

On increasing the blob diameter and other settings; that can be adjusted in SpotMetrics as they are just user defined parameters. So that probably will not be a problem to edit in the plugin. However the video processing might not be. So the whole purpose of SpotMetrics (or at least on of them) is to automate the tedious steps of processing the videos.

What can be done, however is to parameterize more options to cover more use cases. When this plugin was created it was catered mostly to dealing with the videos from Stavros Hadjisolomou who used it in his research. One major part of getting good results was having access to videos for testing. If I am just blindly adjusting the software then I cannot ensure the quality of its output. It is usually better to have a 2 part collaboration.

  1.  Collaboration between you and Mr. Hadjisolomou on the quality of the videos
  2.  Collaboration between you and I on testing the videos and what options are needed

It may be true that SpotMetrics wasn't designed for videos with very large spots, it also was not designed to take in pre-processed videos. This might be a valid use case but I would need test videos to use in developing a new feature. Also any feature developed should be applicable to anyone who wants to use the plugin.
